### ISSUE TITLE
Add support for Homebrew or GitHub releases

### ISSUE THREAD

**Issue by guidomb** [macmade/xcode-coveralls#2]
It would be nice to be able to install this using homebrew or maybe release a .pkg using GitHub releases. This would avoid having to compile to project in TravisCI.

**Comment by macmade** [comment]
Thanks for the request : )

I'll try to see if I can do this through homebrew.
Otherwise I'll do a .pkg

**Comment by macmade** [comment]
A pull request has been sent to Homebrew: https://github.com/Homebrew/homebrew/pull/41576

**Comment by macmade** [comment]
So looks like this is not popular enough. Sorry...

**Comment by guidomb** [comment]
Really I didn't know they have such restrictions. :-(

**Comment by bfontaine** [comment]
Note that you can maintain your on Homebrew tap (= repo). Create a GitHub repository like `homebrew-foobar` (replace `foobar` with whatever you want), then add your formulae in it.

Users can then install your programs using `brew install macmade/foobar/theformulaname`. For example, if you add the `xcode-coveralls.rb` formula, people can then install it with `brew install macmade/foobar/theformulaname`. They’ll get updates when you’ll update the formula, like the core Homebrew repository.

**Comment by guidomb** [comment]
OK I think that is good enough.
Thanks!

**Comment by macmade** [comment]
@bfontaine Thanks a lot for the suggestion!

**Comment by macmade** [comment]
@guidomb Ok, I created a tap with a formula for xcode-coveralls.
You can now install it using:

```
brew install macmade/tap/xcode-coveralls
```

**Comment by guidomb** [comment]
Cool thanks!
