### ISSUE TITLE
fail to install xcode-coverall on my mac machine

### ISSUE THREAD

**Issue by helenren** [macmade/xcode-coveralls#5]
Running this command to install: brew install macmade/tap/xcode-coveralls from Terminal.

Hit the error:

ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/Release/xcode-coveralls normal x86_64
(1 failure)

**Comment by macmade** [comment]
Thanks for the report.  
The homebrew tap has been updated, so everything should be fine now.
